import type { Metadata } from "next";

import { ConfigProvider } from "antd";

import "./globals.css";

export const metadata: Metadata = {
  title: "Simple - personal blog with interesting content",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <ConfigProvider
        theme={{
          token: { colorPrimary: "#1e1e1e", colorPrimaryHover: "#1e1e1ecc" },
        }}
      >
        <body>{children}</body>
      </ConfigProvider>
    </html>
  );
}
